# IP of the collector you are trying to connect to (BGProutes.io's side)
collector_ip: 
# Port to which the proxy must connect
collector_port:
# ID of your collector (<asn>_<IP>)
collector_id:
# Token taken from the website
cert_token:
# Directory inside the docker container where the certificates will be stored
internal_directory:
# Do we need to use TLS ?
use_tls:
# Local Addr to bind
local_addr:
# Local Port to bind
local_port:
